# Generated by Django 3.0.3 on 2020-02-10 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auction_final_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='bid_value',
            field=models.IntegerField(default=5),
        ),
    ]
