# Generated by Django 3.0.3 on 2020-02-10 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auction_bid_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='highest_bid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auction',
            name='bid_value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
