# Generated by Django 3.0.3 on 2020-02-10 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_auto_20200211_0044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='highest_bid',
        ),
    ]
