# Generated by Django 3.0.3 on 2020-02-14 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_auction_auction_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='auction_duration',
            field=models.CharField(max_length=200),
        ),
    ]
