# Generated by Django 3.0.3 on 2020-02-14 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_auto_20200214_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='auction_duration',
        ),
        migrations.AddField(
            model_name='auction',
            name='deadline_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
