# Generated by Django 3.0.3 on 2020-02-14 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_auto_20200214_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='deadline_date',
            field=models.CharField(max_length=300),
        ),
    ]
