# Generated by Django 2.2.5 on 2020-02-14 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_auto_20200214_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='image',
            field=models.ImageField(blank=True, default='auction_images/rick.jpeg', upload_to='auction_images/'),
        ),
    ]
