# Generated by Django 2.2.5 on 2020-02-15 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_auto_20200214_1846'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllBids',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bids_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.Bid')),
            ],
        ),
    ]
