# Generated by Django 2.2.5 on 2020-02-15 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0021_auto_20200215_0128'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BidsHistory',
        ),
    ]
